### ISSUE TITLE
Performance issues 

### ISSUE THREAD

**Issue by molbal** [elementbound/gms-layer-core#1]
Hello,

I get performance issues when I try typing the following sequence:
N E V E R   G O N N A   L E T   Y O U   D O W N

Thank you for your assistance,
R. Ick A. Stley

**Comment by elementbound** [comment]
Hi! 

Thanks for the feedback! I have looked into the issue and I was able to reproduce it. We have provided a quick patch for it in the latest commit. I hope it will be statisfactory, I have noticed significant performance improvements on my workstation. 

Sincerely, 
elementbound
